# Welcome to Numpy

In [1]:
import numpy as np

In [2]:
print("Hello World!")

Hello World!


***This is Game***

In [3]:
import sklearn

In [4]:
i = 50

In [5]:
print(7)

7


In [6]:
i

50

In [7]:
k = 30

In [8]:
k

30

In [9]:
f = 40

In [10]:
f

40

In [11]:
                                              #Let's Start the grill------

In [12]:
myarr = np.array([3,6,32,7], np.int8)

In [13]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [14]:
myarr[1]

6

In [15]:
myarr[0]

3

In [16]:
myarr[-1]

7

In [17]:
myarr[-2]

32

In [18]:
myarr2 = np.array([[12,3,5,30,50]],  np.int8)

In [19]:
myarr2

array([[12,  3,  5, 30, 50]], dtype=int8)

In [20]:
myarr2[0,1]

3

In [21]:
myarr2.shape

(1, 5)

In [22]:
myarr2.dtype

dtype('int8')

# Array creation: Conversion from other Python structures

**2D array**

In [23]:
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
listarr.dtype

dtype('int32')

In [26]:
listarr.shape

(3, 3)

In [27]:
listarr.size

9

# Converting dtype

In [28]:
listarr3 = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int8)

In [29]:
listarr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [30]:
listarr3.dtype

dtype('int8')

# Various intrinsic functions:- 

In [31]:
zeros = np.zeros((2,5))

In [32]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
zeros.dtype

dtype('float64')

In [34]:
zeros.shape

(2, 5)

In [35]:
zeros.size

10

In [36]:
rng = np.arange(15)

In [37]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
lspace = np.linspace(1,5,12)

In [39]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [40]:
lspace2 = np.linspace(1,12,6)

In [41]:
lspace2

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [42]:
emp = np.empty((3,3))

In [43]:
emp

array([[4.67296746e-307, 1.69121096e-306, 6.23047842e-307],
       [2.22526399e-307, 6.23053614e-307, 7.56592338e-307],
       [9.34588061e-307, 9.34531022e-307, 3.62651150e-317]])

In [44]:
emp_like =  np.empty_like(lspace2)

In [45]:
emp_like

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [48]:
ide = np.identity(45)

In [49]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [50]:
ide.shape

(45, 45)

In [51]:
arr = np.arange(99)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
arr.shape

(99,)

In [55]:
arr = arr.reshape(3,33)

In [56]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr.shape

(3, 33)

In [58]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr.shape

(3, 33)

In [60]:
arr = arr.ravel()

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr.shape

(99,)

# Axis of NumPy Array:-

In [63]:
x =[[1,2,3],[4,5,6],[7,1,0]]

In [64]:
ar =np.array(x)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.sum(axis=0)

array([12,  8,  9])

In [67]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [68]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [69]:
ar.flat

In [70]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [71]:
ar.ndim

2

In [72]:
arr.ndim

1

In [73]:
listarr3.ndim

2

In [74]:
ar.size

9

In [76]:
ar.nbytes

36

In [78]:
ar.dtype

dtype('int32')

# Use of argmax(), argmin(), argsort() functions:-

In [118]:
one = np.array([5,2,93,649,2,63])

In [119]:
one.argmax()

3

In [120]:
one.argmin()

1

In [121]:
one.argsort()

array([1, 4, 0, 5, 2, 3], dtype=int64)

In [122]:
one.dtype

dtype('int32')

# Some more examples:-

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
ar.argmin()

8

In [91]:
ar.argmax()

6

In [92]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [93]:
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [94]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [95]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [96]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [97]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [98]:
ar.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [99]:
ar.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [101]:
ar[2,0]

7

In [105]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [106]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

# Matrix operation:-

In [107]:
ar2 = np.array([[0,1,7],[6,5,4],[3,2,1]])

In [108]:
ar2

array([[0, 1, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [110]:
ar * ar2

array([[ 0,  2, 21],
       [24, 25, 24],
       [21,  2,  0]])

In [111]:
ar + ar2

array([[ 1,  3, 10],
       [10, 10, 10],
       [10,  3,  1]])

In [112]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [123]:
ar.sum()

29

In [124]:
ar.max()

7

In [125]:
ar.min()

0

In [126]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [128]:
np.count_nonzero(ar)

8

In [129]:
type(arr)

numpy.ndarray

In [131]:
type(listarr3)

numpy.ndarray

In [132]:
type(ar)

numpy.ndarray

In [133]:
type(lspace)

numpy.ndarray

In [134]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [135]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [136]:
ar[1,2] = 0

In [137]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [ ]:
                             # Refer this website for Numpy methods & attributes "Scipy.org"

In [138]:
import sys

In [139]:
py_ar = [0,4,55,2]

In [140]:
np_ar = np.array(py_ar)

In [141]:
sys.getsizeof(1) * len(py_ar)

112

In [142]:
np_ar

array([ 0,  4, 55,  2])

In [143]:
np_ar.itemsize * np_ar.size

16

In [144]:
py_ar2 = [12,48,6,34,18]

In [145]:
np_ar2 = np.array(py_ar2)

In [146]:
np_ar2

array([12, 48,  6, 34, 18])

In [147]:
sys.getsizeof(1) * len(py_ar2)

140

In [148]:
np_ar2.itemsize * np_ar2.size

20